gate-sawfish: 
  intersection_tresh: 0
  confidence_tresh: .6
gate-shark: 
  intersection_tresh: 0
  confidence_tresh: .6
gate: 
  intersection_tresh: 0
  confidence_tresh: .6
torpedo-poster: 
  intersection_tresh: 0
  confidence_tresh: .6
torpedo-target: 
  intersection_tresh: 0
  confidence_tresh: .6
sawfish: 
  intersection_tresh: 0
  confidence_tresh: .6
shark: 
  intersection_tresh: 0
  confidence_tresh: .6
bin: 
  intersection_tresh: 0
  confidence_tresh: .6
bin-inner: 
  intersection_tresh: 0
  confidence_tresh: .6
table: 
  intersection_tresh: 0
  confidence_tresh: .6
path: 
  intersection_tresh: 0
  confidence_tresh: .6
red-slalom: 
  intersection_tresh: 1
  confidence_tresh: .6
white-slalom: 
  intersection_tresh: 1
  confidence_tresh: .6
yellow-box: 
  intersection_tresh: 0
  confidence_tresh: .6
pink-box: 
  intersection_tresh: 0
  confidence_tresh: .6
spoon: 
  intersection_tresh: 1
  confidence_tresh: .6
bottle: 
  intersection_tresh: 1
  confidence_tresh: .6